import turtle
screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("tan")
t = turtle.Turtle()

t.penup()
t.goto(0,0)
t.pendown()
t.begin_fill()
t.fillcolor("grey")
t.circle(20)
t.end_fill()
t.write("Hello",font=("Arial",30,"bold"),align="center")
round = input("press Enter to Continue: ")
t.clear()


t.penup()
t.goto(0,0)
t.pendown()
screen.addshape("messi.gif")
t.shape('messi.gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(40,200)
t.pendown()
screen.addshape("neymar.gif")
t.shape('neymar.gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(70,50)
t.pendown()
t.write("I like soccer my two idols are on screen",font=("Arial",25,"bold"),align="center")
t.penup()
t.goto(0,-200)
t.pendown()
for i in range(4):
    t.forward(20)
    t.left(90)
round = input("press Enter to Continue: ")
t.clear()
screen.bgcolor('tan')


t.penup()
t.goto(-50,0)
t.pendown()
screen.bgcolor('aqua')
screen.addshape('pizza.gif')
t.shape('pizza.gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(150,250)
t.pendown()
t.write("I love pizza and fries",font=("Arial",15,"bold"),align="center")
t.penup()
t.goto(150,-100)
t.pendown()
screen.addshape('fry.gif')
t.shape('fry.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(-100,-200)
t.pendown()
for i in range(14):
    t.forward(50)
    t.left(25)


round = input("press Enter to Continue: ")
t.clear()
screen.bgcolor('yellow')
t.penup()
t.goto(0,0)
t.pendown()
screen.addshape('tik.gif')
t.shape('tik.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(50,50)
t.pendown()
screen.addshape('sleep.gif')
t.shape('sleep.gif')
t.stamp()
t.shape('classic')
t.pendown()
t.write("I like napping and playing soccer eating and gaming",font=("Arial",15,"bold"),align="center")
t.penup()
t.goto(-100,-200)
t.pendown()
for i in range(80):
    t.forward(30)
    t.left(12)



round = input("press Enter to Continue: ")
t.clear()
screen.bgcolor('grey')
t.penup()
t.goto(0,0)
t.pendown()
screen.addshape('fly.gif')
t.shape('fly.gif')
t.stamp()
t.shape('classic')
t.write("I like south asian movies",font=("Arial",15,"bold"),align="center")
t.penup()
t.goto(90,150)
t.pendown()
screen.addshape('bug.gif')
t.shape('bug.gif')
t.stamp()
t.shape('bug.gif')
t.penup()
t.goto(-100,-200)
t.pendown()
for i in range(90):
    t.forward(4)
    t.left(6)


round = input("press Enter to Continue: ")
t.clear()
screen.bgcolor('purple')
t.penup()
t.goto(0,0)
t.pendown()
screen.addshape('soccer.gif')
t.shape('soccer.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0,0)
t.pendown()
screen.addshape('bug.gif')
t.shape('bug.gif')
t.stamp()
t.shape('classic.gif')
t.penup()
t.goto(-100,-200)
t.pendown()
for i in range(3):
    t.forward(40)
    t.left(90)
    t.forward(10)
round = input("press Enter to Continue: ")

t.clear()
screen.bgcolor('green')
t.penup()
t.goto(0,0)
t.pendown()
screen.addshape("soccer.gif")
t.shape('soccer.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0,0)
t.pendown()
screen.addshape("neymar.gif")
t.shape('neymar.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(50,150)
t.pendown()
t.write("I like soccer and neymar is my fav",font=("Arial",15,"bold"),align="center")
t.penup()
t.goto(-100,-200)
t.pendown()
for i in range(18):
    t.forward(79)
    t.left(45)
round = input("press Enter to Continue: ")
t.clear()
screen.bgcolor('tan')
t.penup()
t.goto(0,0)
t.pendown()
t.write("we done gang",font=("Arial",15,"bold"),align="center")
t.penup()
t.goto(-100,-200)
t.pendown()
for i in range(14):
    t.forward(50)
    t.left(25)
    t.right(45)




turtle.done()